import hiddenlayer as hl

transforms_pool_upsample = [hl.transforms.FoldDuplicates(), 
              #hl.transforms.Fold("Constant > Resize", "Resize", name="Resize"),
              hl.transforms.Fold("Conv > LeakyRelu", "ConvLRelu", name="ConvLRelu"),
              hl.transforms.Prune("Constant"), 
              hl.transforms.Prune("Concat"),
              hl.transforms.Fold("Tanh > Mul", "TanhMul", name="TanhMul"),
              hl.transforms.Fold("ConvLRelu > ConvLRelu > MaxPool", "ConvConvLReluPool", name="ConvConvLReluPool", append_shape=True),
              hl.transforms.Fold("Resize > ConvLRelu > ConvLRelu", "UpsConvConvLRelu", name="UpsConvConvLRelu", append_shape=True),
              hl.transforms.Fold("ConvLRelu > ConvLRelu", "ConvConvLRelu", name="ConvConvLRelu", append_shape=True),
              hl.transforms.Fold("Resize > Conv", "UpsConv", name="UpsConv", append_shape=True),
              hl.transforms.Fold("UpsConv > LeakyRelu", "UpsConvLRelu", name="UpsConvLRelu", append_shape=True),
              hl.transforms.Fold("Conv > TanhMul", "ConvTanhMul", name="ConvTanhMul"),
              hl.transforms.Fold("Conv > Sigmoid", "ConvSigmoid", name="ConvSigmoid"),
              ]

transforms_conv_strides = [hl.transforms.FoldDuplicates(), 
              #hl.transforms.Fold("Constant > Resize", "Resize", name="Resize"),
              hl.transforms.Fold("Conv > LeakyRelu", "ConvLRelu", name="ConvLRelu"),
              hl.transforms.Fold("ConvTranspose > LeakyRelu", "TConvLRelu", name="TConvLRelu"),
              hl.transforms.Prune("Constant"), 
              hl.transforms.Prune("Concat"),
              hl.transforms.Fold("Tanh > Mul", "TanhMul", name="TanhMul"),
              hl.transforms.Fold("ConvLRelu > ConvLRelu > MaxPool", "ConvConvLReluPool", name="ConvConvLReluPool", append_shape=True),
              hl.transforms.Fold("Resize > ConvLRelu > ConvLRelu", "UpsConvConvLRelu", name="UpsConvConvLRelu", append_shape=True),
              hl.transforms.Fold("ConvLRelu > ConvLRelu", "ConvConvLRelu", name="ConvConvLRelu", append_shape=True),
              hl.transforms.Fold("TConvLRelu > ConvLRelu", "TConvConvLRelu", name="TConvConvLRelu", append_shape=True),
              hl.transforms.Fold("Resize > Conv", "UpsConv", name="UpsConv", append_shape=True),
              hl.transforms.Fold("UpsConv > LeakyRelu", "UpsConvLRelu", name="UpsConvLRelu", append_shape=True),
              hl.transforms.Fold("UpsConv > TanhMul", "UpsConvTanhMul", name="UpsConvTanhMul", append_shape=True),
              hl.transforms.Fold("UpsConv > Sigmoid", "UpsConvSigmoid", name="UpsConvSigmoid", append_shape=True),
              hl.transforms.Fold("Conv > TanhMul", "ConvTanhMul", name="ConvTanhMul"),
              hl.transforms.Fold("Conv > Sigmoid", "ConvSigmoid", name="ConvSigmoid"),
              ]